import { writeFile, readFile } from "node:fs/promises";

const { url } = import.meta;
const { version } = JSON.parse(await readFile(new URL("../package.json", url)));

await writeFile(
  new URL("../src/version.ts", url),
  `\
// This file is autogenerated by /scripts/postversion.mjs
export const version = ${JSON.stringify(version)};
`,
);
